jobs:
  test:
    docker:
      - image: 'cimg/node:13.12-browser'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
orbs:
  browser-tools: circleci/browser-tools@x.y
  
version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
